### ISSUE TITLE
Sign up security issue

### ISSUE THREAD

**Issue by quinnturner** [satishbabariya/nodejs-boilerplate#359]
During sign up, you should not specify whether an account exists or not.

```ts
if (error.name === 'MongoError' && error.code === 11000) {
    // Duplicate username
    throw new Error('User already exist!');
}
```

Similarly, you should not specify whether a user exists during login vs. password incorrect. Both are leaking potentially sensitive information whether a user account exists.

A better implementation for sign-in would be to say that the credentials are invalid. Similarly, for registering, it would be to just say check your email regardless of whether you send an email for confirmation.

**Comment by satishbabariya** [comment]
@quinnturner valid point for sure. you can put one pr for that if it's possible.
